openapi: 3.0.3
info:
  title: Movie Collection Management API - Internal
  description: |
    Внутренний API для получения полного списка фильмов в коллекции.
    Этот endpoint предназначен для внутреннего использования сервисами.
  version: 1.0.0
  contact:
    name: API Support
    email: ae.troshkin@gmail.com
servers:
  - url: http://localhost:9001/service1/api/v1
    description: Production server

paths:
  /internal/movies:
    get:
      tags:
        - Internal
      summary: Получить все фильмы
      description: Возвращает все фильмы в коллекции
      responses:
        '200':
          description: Все фильмы успешно получены
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Movie:
      type: object
      required:
        - id
        - name
        - coordinates
        - creationDate
        - length
        - director
      properties:
        id:
          type: integer
          description: Уникальный идентификатор фильма (генерируется автоматически)
          minimum: 1
          example: 1
        name:
          type: string
          description: Название фильма
          minLength: 1
          example: "Криминальное чтиво"
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date-time
          description: Дата создания записи (генерируется автоматически)
          example: "2024-01-15T10:30:00Z"
        oscarsCount:
          type: integer
          description: Количество полученных Оскаров
          minimum: 1
          nullable: true
          example: 1
        totalBoxOffice:
          type: number
          format: double
          description: Общие сборы фильма
          minimum: 0
          nullable: true
          example: 214179088.0
        length:
          type: integer
          format: int64
          description: Длительность фильма в минутах
          minimum: 1
          example: 154
        director:
          $ref: '#/components/schemas/Person'
        genre:
          $ref: '#/components/schemas/MovieGenre'
        operator:
          $ref: '#/components/schemas/Person'

    Coordinates:
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: integer
          description: Координата X
          minimum: -650
          example: 100
        y:
          type: number
          format: float
          description: Координата Y
          minimum: -612
          example: 50.5

    Person:
      type: object
      required:
        - name
        - passportID
        - hairColor
        - location
      nullable: true
      properties:
        name:
          type: string
          description: Имя человека (режиссера или оператора)
          minLength: 1
          example: "Квентин Тарантино"
        passportID:
          type: string
          description: Номер паспорта (уникальный)
          minLength: 8
          example: "AB1234567"
        eyeColor:
          $ref: '#/components/schemas/EyeColor'
        hairColor:
          $ref: '#/components/schemas/HairColor'
        nationality:
          $ref: '#/components/schemas/Country'
        location:
          $ref: '#/components/schemas/Location'

    Location:
      type: object
      required:
        - x
        - y
        - z
      properties:
        x:
          type: number
          format: double
          description: Координата X местоположения
          example: 12.34
        y:
          type: integer
          format: int64
          description: Координата Y местоположения
          example: 56
        z:
          type: integer
          description: Координата Z местоположения
          example: 78

    MovieGenre:
      type: string
      description: Жанр фильма
      enum:
        - COMEDY
        - ADVENTURE
        - TRAGEDY
        - SCIENCE_FICTION
      example: COMEDY

    EyeColor:
      type: string
      description: Цвет глаз
      nullable: true
      enum:
        - GREEN
        - RED
        - BLACK
        - ORANGE
      example: GREEN

    HairColor:
      type: string
      description: Цвет волос
      enum:
        - GREEN
        - RED
        - BLACK
        - BLUE
      example: BLACK

    Country:
      type: string
      description: Страна
      nullable: true
      enum:
        - FRANCE
        - VATICAN
        - SOUTH_KOREA
      example: FRANCE

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Краткое описание ошибки
          example: "BAD_REQUEST"
        message:
          type: string
          description: Подробное сообщение об ошибке
          example: "Поле 'name' не может быть пустым"
        timestamp:
          type: string
          format: date-time
          description: Время возникновения ошибки
          example: "2024-01-15T10:30:00Z"
        path:
          type: string
          description: Путь запроса, где произошла ошибка
          example: "/api/v1/movies"

  responses:
    BadRequest:
      description: Некорректный запрос - нарушены ограничения целостности данных
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "BAD_REQUEST"
            message: "Некорректный запрос"
            timestamp: "2024-01-15T10:30:00Z"
            path: "/api/v1/movies"
    InternalServerError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "INTERNAL_SERVER_ERROR"
            message: "Произошла внутренняя ошибка сервера"
            timestamp: "2024-01-15T10:30:00Z"
            path: "/api/v1/movies"

tags:
  - name: Internal
    description: Внутренние операции для получения полного списка фильмов

