version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: movie-postgres
    environment:
      POSTGRES_DB: movie_db
      POSTGRES_USER: hulumulumulus
      POSTGRES_PASSWORD: movie_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - movie-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U movie_user -d movie_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  movie-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/movie_db
      SPRING_DATASOURCE_USERNAME: movie_user
      SPRING_DATASOURCE_PASSWORD: movie_password
    ports:
      - "8080:8080"
    networks:
      - movie-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  movie-network:
    driver: bridge

