spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/movie_db_prod}
    username: ${DB_USERNAME:movie_user_prod}
    password: ${DB_PASSWORD:movie_password_prod}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        jdbc:
          batch_size: 50

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: WARN
    ru.itmo.soa: INFO
    org.hibernate.SQL: WARN
  file:
    name: /var/log/movie-service/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

