#targets:
#  $default:
#    builders:
#      source_gen|combining_builder:
#        options:
#          build_extensions:
#            '^lib/{{path}}.dart': 'lib/gen/{{path}}.g.dart'
#      freezed:
#        options:
#          build_extensions:
#            '^lib/{{path}}.dart': 'lib/gen/{{path}}.g.dart'